"""Module implementation."""
# Generated by Django 4.2.7 on 2025-07-19 20:53

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SearchIndex",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content_type", models.CharField(max_length=50)),
                ("object_id", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("search_vector", django.contrib.postgres.search.SearchVectorField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "search_index",
                "indexes": [
                    models.Index(fields=["content_type", "object_id"], name="search_inde_content_2ee61b_idx"),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["search_vector"], name="search_inde_search__511705_gin"
                    ),
                ],
                "unique_together": {("content_type", "object_id")},
            },
        ),
    ]
