"""Module implementation."""
# Generated by Django 4.2.7 on 2025-07-19 20:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        ("trials", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "provider",
                    models.CharField(
                        choices=[("stripe", "Stripe"), ("paypal", "PayPal")], default="stripe", max_length=20
                    ),
                ),
                ("provider_customer_id", models.CharField(blank=True, max_length=255)),
                ("provider_payment_method_id", models.CharField(blank=True, max_length=255)),
                ("card_last4", models.CharField(blank=True, max_length=4)),
                ("card_brand", models.CharField(blank=True, max_length=20)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_methods_new",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "db_table": "payments_payment_methods",
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("provider_subscription_id", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("trialing", "Trialing"),
                            ("active", "Active"),
                            ("past_due", "Past Due"),
                            ("canceled", "Canceled"),
                            ("unpaid", "Unpaid"),
                        ],
                        default="trialing",
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("current_period_start", models.DateTimeField(blank=True, null=True)),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                ("cancel_at_period_end", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_subscriptions",
                        to="companies.company",
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="payments.paymentmethod"
                    ),
                ),
                (
                    "trial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_subscriptions",
                        to="trials.trial",
                    ),
                ),
            ],
            options={
                "db_table": "payments_subscriptions",
            },
        ),
        migrations.CreateModel(
            name="PaymentEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("provider", models.CharField(default="stripe", max_length=20)),
                ("event_type", models.CharField(max_length=50)),
                ("provider_event_id", models.CharField(max_length=255, unique=True)),
                ("data", models.JSONField()),
                ("processed", models.BooleanField(default=False)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "payment_events",
                "indexes": [
                    models.Index(
                        fields=["provider", "event_type", "-created_at"], name="payment_eve_provide_e96af2_idx"
                    ),
                    models.Index(fields=["processed", "created_at"], name="payment_eve_process_7aa9e5_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("provider_invoice_id", models.CharField(blank=True, max_length=255)),
                ("invoice_number", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("open", "Open"),
                            ("paid", "Paid"),
                            ("void", "Void"),
                            ("uncollectible", "Uncollectible"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("amount_due", models.DecimalField(decimal_places=2, max_digits=10)),
                ("amount_paid", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                ("invoice_pdf", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="invoices", to="payments.subscription"
                    ),
                ),
            ],
            options={
                "db_table": "payments_invoices",
            },
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(fields=["company", "-created_at"], name="payments_su_company_2e36ee_idx"),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(fields=["status", "current_period_end"], name="payments_su_status_488f2e_idx"),
        ),
        migrations.AddIndex(
            model_name="paymentmethod",
            index=models.Index(fields=["company", "-created_at"], name="payments_pa_company_38c2ac_idx"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["subscription", "-created_at"], name="payments_in_subscri_de30b3_idx"),
        ),
    ]
