# Generated by Django 4.2.17 on 2025-07-20 09:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="invoice",
            name="payments_in_subscri_de30b3_idx",
        ),
        migrations.RemoveIndex(
            model_name="paymentevent",
            name="payment_eve_provide_e96af2_idx",
        ),
        migrations.RemoveIndex(
            model_name="paymentevent",
            name="payment_eve_process_7aa9e5_idx",
        ),
        migrations.RemoveIndex(
            model_name="paymentmethod",
            name="payments_pa_company_38c2ac_idx",
        ),
        migrations.RemoveIndex(
            model_name="subscription",
            name="payments_su_company_2e36ee_idx",
        ),
        migrations.RemoveIndex(
            model_name="subscription",
            name="payments_su_status_488f2e_idx",
        ),
        migrations.AlterModelTable(
            name="invoice",
            table=None,
        ),
        migrations.AlterModelTable(
            name="paymentevent",
            table=None,
        ),
        migrations.AlterModelTable(
            name="paymentmethod",
            table=None,
        ),
        migrations.AlterModelTable(
            name="subscription",
            table=None,
        ),
    ]
