"""Module implementation."""
# Generated by Django 4.2.7 on 2025-07-18 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                ("value", models.JSONField()),
                ("description", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "system_configs",
            },
        ),
        migrations.CreateModel(
            name="AdminAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("user_banned", "User Banned"),
                            ("user_unbanned", "User Unbanned"),
                            ("trial_approved", "Trial Approved"),
                            ("trial_rejected", "Trial Rejected"),
                            ("trial_featured", "Trial Featured"),
                            ("system_config", "System Configuration"),
                            ("bulk_action", "Bulk Action"),
                        ],
                        max_length=50,
                    ),
                ),
                ("target_model", models.CharField(max_length=50)),
                ("target_id", models.IntegerField(blank=True, null=True)),
                ("details", models.JSONField(default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "admin_actions",
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="admin_actio_timesta_188238_idx"
                    ),
                    models.Index(
                        fields=["admin", "-timestamp"],
                        name="admin_actio_admin_i_d76eac_idx",
                    ),
                    models.Index(
                        fields=["action_type", "-timestamp"],
                        name="admin_actio_action__524e96_idx",
                    ),
                ],
            },
        ),
    ]
