# Generated by Django 4.2.17 on 2025-07-20 09:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="contactmessage",
            table=None,
        ),
        migrations.AlterModelTable(
            name="notification",
            table=None,
        ),
    ]
